[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/radio/"
to = "/actualites/audio/radio/"

[[redirects]]
from = "/catarina-mo/actualites/"
to = "/personnes/catarina-mo/actualites/"

[[redirects]]
from = "/actualites/media-independant/"
to = "/actualites/medias/media-independant/"

[[redirects]]
from = "/actualites/article/"
to = "/actualites/format/article/"

[[redirects]]
from = "/actualites/obsolescence-numerique/"
to = "/actualites/numerique/obsolescence-numerique/"

[[redirects]]
from = "/actualites/festival/"
to = "/actualites/format/festival/"

[[redirects]]
from = "/actualites/ecologie-numerique-1/"
to = "/actualites/numerique/ecologie-numerique-1/"

[[redirects]]
from = "/actualites/2026-02-10-rd-ney-york-time/"
to = "/actualites/2026-02-10-rd-new-york-time/"

[[redirects]]
from = "/catarina-mo/"
to = "/personnes/catarina-mo/"

[[redirects]]
from = "/cylian-guibert/"
to = "/personnes/cylian-guibert/"

[[redirects]]
from = "/adrien-dozias/"
to = "/personnes/adrien-dozias/"

[[redirects]]
from = "/equipe-editoriale/"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/actualites/cooperative/"
to = "/actualites/format/cooperative/"

[[redirects]]
from = "/yufan-zhou/"
to = "/personnes/yufan-zhou/"

[[redirects]]
from = "/actualites/infrastructure-numerique/"
to = "/actualites/numerique/infrastructure-numerique/"

[[redirects]]
from = "/actualites/humanites-numeriques/"
to = "/actualites/numerique/humanites-numeriques/"

[[redirects]]
from = "/actualites/museographie/"
to = "/actualites/scenographie/museographie/"

[[redirects]]
from = "/melanie-arriberouge/actualites/"
to = "/personnes/melanie-arriberouge/actualites/"

[[redirects]]
from = "/actualites/theorie-du-design-1/"
to = "/actualites/recherche/theorie-du-design-1/"

[[redirects]]
from = "/mathilde-bezard-falgas/"
to = "/personnes/mathilde-bezard-falgas/"

[[redirects]]
from = "/maxime-zoffoli/"
to = "/personnes/maxime-zoffoli/"

[[redirects]]
from = "/actualites/nouveau-media/"
to = "/actualites/medias/nouveau-media/"

[[redirects]]
from = "/karl-pineau/actualites/"
to = "/personnes/karl-pineau/actualites/"

[[redirects]]
from = "/karl-pineau/"
to = "/personnes/karl-pineau/"

[[redirects]]
from = "/actualites/lowtech/"
to = "/actualites/ecologie/lowtech/"

[[redirects]]
from = "/victoria-braud/actualites/"
to = "/personnes/victoria-braud/actualites/"

[[redirects]]
from = "/actualites/typographie/typotheque/"
to = "/actualites/graphic-design/typotheque/"

[[redirects]]
from = "/actualites/typotheque/"
to = "/actualites/graphic-design/typotheque/"

[[redirects]]
from = "/actualites/bande-dessinee/"
to = "/actualites/narration/bande-dessinee/"

[[redirects]]
from = "/actualites/accessibilite/"
to = "/actualites/numerique/accessibilite/"

[[redirects]]
from = "/mathilde-bezard-falgas/actualites/"
to = "/personnes/mathilde-bezard-falgas/actualites/"

[[redirects]]
from = "/actualites/typographie/"
to = "/actualites/graphic-design/typographie/"

[[redirects]]
from = "/actualites/collaboratif/"
to = "/actualites/sciences-participatives/collaboratif/"

[[redirects]]
from = "/actualites/identite-visuelle/"
to = "/actualites/graphic-design/identite-visuelle/"

[[redirects]]
from = "/actualites/limite-numerique/"
to = "/actualites/numerique/limite-numerique/"

[[redirects]]
from = "/yufan-zhou/actualites/"
to = "/personnes/yufan-zhou/actualites/"

[[redirects]]
from = "/actualites/2025-12-23-festival-osint-gaite-lyrique/"
to = "/actualites/2026-03-06-festival-osint-gaite-lyrique/"

[[redirects]]
from = "/actualites/cyberfeminisme/"
to = "/actualites/feminisme/cyberfeminisme/"

[[redirects]]
from = "/actualites/conference/"
to = "/actualites/format/conference/"

[[redirects]]
from = "/violette-vigneron/actualites/"
to = "/personnes/violette-vigneron/actualites/"

[[redirects]]
from = "/actualites/co-creation/"
to = "/actualites/sciences-participatives/co-creation/"

[[redirects]]
from = "/actualites/atelier-participatif/"
to = "/actualites/sciences-participatives/atelier-participatif/"

[[redirects]]
from = "/actualites/techno-democratie/"
to = "/actualites/democratie/techno-democratie/"

[[redirects]]
from = "/actualites/numerique-responsable/"
to = "/actualites/numerique/numerique-responsable/"

[[redirects]]
from = "/actualites/non-binaire/"
to = "/actualites/genre/non-binaire/"

[[redirects]]
from = "/actualites/reseau-social/"
to = "/actualites/medias/reseau-social/"

[[redirects]]
from = "/actualites/transition-numerique/"
to = "/actualites/numerique/transition-numerique/"

[[redirects]]
from = "/melanie-arriberouge/"
to = "/personnes/melanie-arriberouge/"

[[redirects]]
from = "/actualites/motion/"
to = "/actualites/graphic-design/motion/"

[[redirects]]
from = "/actualites/association/"
to = "/actualites/format/association/"

[[redirects]]
from = "/actualites/information-design/"
to = "/actualites/graphic-design/information-design/"

[[redirects]]
from = "/actualites/documentaire/"
to = "/actualites/format/documentaire/"

[[redirects]]
from = "/actualites/design-editorial/"
to = "/actualites/graphic-design/design-editorial/"

[[redirects]]
from = "/actualites/signaletique/"
to = "/actualites/graphic-design/signaletique/"

[[redirects]]
from = "/olivier-ahehehinnou/"
to = "/personnes/olivier-ahehehinnou/"

[[redirects]]
from = "/maxime-zoffoli/actualites/"
to = "/personnes/maxime-zoffoli/actualites/"

[[redirects]]
from = "/actualites/radio/podcast/"
to = "/actualites/audio/podcast/"

[[redirects]]
from = "/actualites/developpement-web/"
to = "/actualites/web/developpement-web/"

[[redirects]]
from = "/actualites/art-numerique/"
to = "/actualites/numerique/art-numerique/"

[[redirects]]
from = "/olivier-ahehehinnou/actualites/"
to = "/personnes/olivier-ahehehinnou/actualites/"

[[redirects]]
from = "/victoria-braud/"
to = "/personnes/victoria-braud/"

[[redirects]]
from = "/violette-vigneron/"
to = "/personnes/violette-vigneron/"

[[redirects]]
from = "/actualites/podcast/"
to = "/actualites/audio/podcast/"

[[redirects]]
from = "/adrien-dozias/actualites/"
to = "/personnes/adrien-dozias/actualites/"

[[redirects]]
from = "/actualites/soutenable/"
to = "/actualites/ecologie/soutenable/"

[[redirects]]
from = "/cylian-guibert/actualites/"
to = "/personnes/cylian-guibert/actualites/"

