[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/radio/index.html"
to = "/actualites/audio/radio/"

[[redirects]]
from = "/catarina-mo/actualites/index.html"
to = "/personnes/catarina-mo/actualites/"

[[redirects]]
from = "/actualites/media-independant/index.html"
to = "/actualites/medias/media-independant/"

[[redirects]]
from = "/actualites/article/index.html"
to = "/actualites/format/article/"

[[redirects]]
from = "/actualites/obsolescence-numerique/index.html"
to = "/actualites/numerique/obsolescence-numerique/"

[[redirects]]
from = "/actualites/festival/index.html"
to = "/actualites/format/festival/"

[[redirects]]
from = "/actualites/ecologie-numerique-1/index.html"
to = "/actualites/numerique/ecologie-numerique-1/"

[[redirects]]
from = "/actualites/2026-02-10-rd-ney-york-time/index.html"
to = "/actualites/2026-02-10-rd-new-york-time/"

[[redirects]]
from = "/catarina-mo/index.html"
to = "/personnes/catarina-mo/"

[[redirects]]
from = "/cylian-guibert/index.html"
to = "/personnes/cylian-guibert/"

[[redirects]]
from = "/adrien-dozias/index.html"
to = "/personnes/adrien-dozias/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/actualites/cooperative/index.html"
to = "/actualites/format/cooperative/"

[[redirects]]
from = "/yufan-zhou/index.html"
to = "/personnes/yufan-zhou/"

[[redirects]]
from = "/actualites/infrastructure-numerique/index.html"
to = "/actualites/numerique/infrastructure-numerique/"

[[redirects]]
from = "/actualites/humanites-numeriques/index.html"
to = "/actualites/numerique/humanites-numeriques/"

[[redirects]]
from = "/actualites/museographie/index.html"
to = "/actualites/scenographie/museographie/"

[[redirects]]
from = "/melanie-arriberouge/actualites/index.html"
to = "/personnes/melanie-arriberouge/actualites/"

[[redirects]]
from = "/actualites/theorie-du-design-1/index.html"
to = "/actualites/recherche/theorie-du-design-1/"

[[redirects]]
from = "/mathilde-bezard-falgas/index.html"
to = "/personnes/mathilde-bezard-falgas/"

[[redirects]]
from = "/maxime-zoffoli/index.html"
to = "/personnes/maxime-zoffoli/"

[[redirects]]
from = "/actualites/nouveau-media/index.html"
to = "/actualites/medias/nouveau-media/"

[[redirects]]
from = "/karl-pineau/actualites/index.html"
to = "/personnes/karl-pineau/actualites/"

[[redirects]]
from = "/karl-pineau/index.html"
to = "/personnes/karl-pineau/"

[[redirects]]
from = "/actualites/lowtech/index.html"
to = "/actualites/ecologie/lowtech/"

[[redirects]]
from = "/victoria-braud/actualites/index.html"
to = "/personnes/victoria-braud/actualites/"

[[redirects]]
from = "/actualites/typographie/typotheque/index.html"
to = "/actualites/graphic-design/typotheque/"

[[redirects]]
from = "/actualites/typotheque/index.html"
to = "/actualites/graphic-design/typotheque/"

[[redirects]]
from = "/actualites/bande-dessinee/index.html"
to = "/actualites/narration/bande-dessinee/"

[[redirects]]
from = "/actualites/accessibilite/index.html"
to = "/actualites/numerique/accessibilite/"

[[redirects]]
from = "/mathilde-bezard-falgas/actualites/index.html"
to = "/personnes/mathilde-bezard-falgas/actualites/"

[[redirects]]
from = "/actualites/typographie/index.html"
to = "/actualites/graphic-design/typographie/"

[[redirects]]
from = "/actualites/collaboratif/index.html"
to = "/actualites/sciences-participatives/collaboratif/"

[[redirects]]
from = "/actualites/identite-visuelle/index.html"
to = "/actualites/graphic-design/identite-visuelle/"

[[redirects]]
from = "/actualites/limite-numerique/index.html"
to = "/actualites/numerique/limite-numerique/"

[[redirects]]
from = "/yufan-zhou/actualites/index.html"
to = "/personnes/yufan-zhou/actualites/"

[[redirects]]
from = "/actualites/2025-12-23-festival-osint-gaite-lyrique/index.html"
to = "/actualites/2026-03-06-festival-osint-gaite-lyrique/"

[[redirects]]
from = "/actualites/cyberfeminisme/index.html"
to = "/actualites/feminisme/cyberfeminisme/"

[[redirects]]
from = "/actualites/conference/index.html"
to = "/actualites/format/conference/"

[[redirects]]
from = "/violette-vigneron/actualites/index.html"
to = "/personnes/violette-vigneron/actualites/"

[[redirects]]
from = "/actualites/co-creation/index.html"
to = "/actualites/sciences-participatives/co-creation/"

[[redirects]]
from = "/actualites/atelier-participatif/index.html"
to = "/actualites/sciences-participatives/atelier-participatif/"

[[redirects]]
from = "/actualites/techno-democratie/index.html"
to = "/actualites/democratie/techno-democratie/"

[[redirects]]
from = "/actualites/numerique-responsable/index.html"
to = "/actualites/numerique/numerique-responsable/"

[[redirects]]
from = "/actualites/non-binaire/index.html"
to = "/actualites/genre/non-binaire/"

[[redirects]]
from = "/actualites/reseau-social/index.html"
to = "/actualites/medias/reseau-social/"

[[redirects]]
from = "/actualites/transition-numerique/index.html"
to = "/actualites/numerique/transition-numerique/"

[[redirects]]
from = "/melanie-arriberouge/index.html"
to = "/personnes/melanie-arriberouge/"

[[redirects]]
from = "/actualites/motion/index.html"
to = "/actualites/graphic-design/motion/"

[[redirects]]
from = "/actualites/association/index.html"
to = "/actualites/format/association/"

[[redirects]]
from = "/actualites/information-design/index.html"
to = "/actualites/graphic-design/information-design/"

[[redirects]]
from = "/actualites/documentaire/index.html"
to = "/actualites/format/documentaire/"

[[redirects]]
from = "/actualites/design-editorial/index.html"
to = "/actualites/graphic-design/design-editorial/"

[[redirects]]
from = "/actualites/signaletique/index.html"
to = "/actualites/graphic-design/signaletique/"

[[redirects]]
from = "/olivier-ahehehinnou/index.html"
to = "/personnes/olivier-ahehehinnou/"

[[redirects]]
from = "/maxime-zoffoli/actualites/index.html"
to = "/personnes/maxime-zoffoli/actualites/"

[[redirects]]
from = "/actualites/radio/podcast/index.html"
to = "/actualites/audio/podcast/"

[[redirects]]
from = "/actualites/developpement-web/index.html"
to = "/actualites/web/developpement-web/"

[[redirects]]
from = "/actualites/art-numerique/index.html"
to = "/actualites/numerique/art-numerique/"

[[redirects]]
from = "/olivier-ahehehinnou/actualites/index.html"
to = "/personnes/olivier-ahehehinnou/actualites/"

[[redirects]]
from = "/victoria-braud/index.html"
to = "/personnes/victoria-braud/"

[[redirects]]
from = "/violette-vigneron/index.html"
to = "/personnes/violette-vigneron/"

[[redirects]]
from = "/actualites/podcast/index.html"
to = "/actualites/audio/podcast/"

[[redirects]]
from = "/adrien-dozias/actualites/index.html"
to = "/personnes/adrien-dozias/actualites/"

[[redirects]]
from = "/actualites/soutenable/index.html"
to = "/actualites/ecologie/soutenable/"

[[redirects]]
from = "/cylian-guibert/actualites/index.html"
to = "/personnes/cylian-guibert/actualites/"

